info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account:
      path: /user/**
      serviceId: account-service
    customer:
      path: /customer/**
      serviceId: customer-service
    resource:
      sensitiveHeaders:
      path: /resource/**
      serviceId: rest-service
    auth:
      sensitiveHeaders:
      #should be same as auth server context path
      path: /auth/**
      serviceId: oauth2-server
      #should be false if server has custom context path
      strip-prefix: false
    add-host-header: true

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
    registerWithEureka: false

server:
  port: 8765

sso:
  client:
    accessTokenUri: http://localhost:7070/auth/oauth/token
    userAuthorizationUri: http://localhost:7070/auth/oauth/authorize
    clientId: clientIdMock
    clientSecret: clientSecretMock
  resource:
    userInfoUri: http://localhost:7070/resource/rest/me